# Pandas 실습
### 1. 실습 데이터 준비
- '서울시 지하철호선별 역별 승하차인원'

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [ ]:
# 데이터 로드
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv')
df

In [ ]:
# 데이터 로드
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv', index_col=False)
df

In [6]:
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

### 2. 데이터 탐색

In [7]:
# 상위 5개의 데이터를 조회
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [9]:
# 데이터프레임의 형태를 확인
df.shape

(19131, 6)

In [10]:
# 하위 데이터 10개를 조회
df.tail(10)

           사용일자  노선명                역명  승차총승객수  하차총승객수      등록일자
19121  20260531  8호선                문정    7350    7431  20260603
19122  20260531  8호선                장지   10401    9980  20260603
19123  20260531  8호선                복정    5988    5340  20260603
19124  20260531  8호선                산성    3611    3915  20260603
19125  20260531  8호선  남한산성입구(성남법원.검찰청)    6905    6413  20260603
19126  20260531  8호선             단대오거리    6782    6559  20260603
19127  20260531  8호선                신흥    3732    3895  20260603
19128  20260531  8호선                수진    4223    3812  20260603
19129  20260531  8호선                모란    3406    2806  20260603
19130  20260531  8호선               남위례    4515    4530  20260603

In [11]:
# 데이터의 사분위수, 표준편차, 분산 등 통계지표를 조회
df.describe()

               사용일자         승차총승객수         하차총승객수          등록일자
count  1.913100e+04   19131.000000   19131.000000  1.913100e+04
mean   2.026052e+07   11811.350740   11759.563640  2.026053e+07
std    8.944833e+00   11836.994181   12011.261965  2.614125e+01
min    2.026050e+07       1.000000       0.000000  2.026050e+07
25%    2.026051e+07    4125.000000    4022.000000  2.026051e+07
50%    2.026052e+07    8396.000000    8135.000000  2.026052e+07
75%    2.026052e+07   15701.500000   15507.500000  2.026053e+07
max    2.026053e+07  101927.000000  115875.000000  2.026060e+07

In [12]:
# 데이터의 데이터타입, 데이터갯수 등을 조회
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19131 entries, 0 to 19130
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    19131 non-null  int64
 1   노선명     19131 non-null  object
 2   역명      19131 non-null  object
 3   승차총승객수  19131 non-null  int64
 4   하차총승객수  19131 non-null  int64
 5   등록일자    19131 non-null  int64
dtypes: int64(4), object(2)
memory usage: 896.9+ KB

In [13]:
# '노선명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['노선명'].nunique()  # 27
df['노선명'].unique()  # array(['5호선', '4호선', '경의선', ...

array(['5호선', '4호선', '경의선', '3호선', '2호선', '1호선', '경인선', '경춘선', '공항철도 1호선',
       '안산선', '과천선', '분당선', '서해선', '수인선', '신림선', '우이신설선', '일산선', '장항선',
       '중앙선', '경원선', '경부선', '경강선', '9호선2~3단계', '9호선', '8호선', '7호선', '6호선'],
      dtype=object)

In [ ]:
# '역명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['역명'].nunique()  # 528
df['역명'].unique()  # array(['방이', '둔촌동', '상일동', '고덕', ...

In [ ]:
# '범주형' - value_counts() : 몇번이나 반복(등장)하는가 확인
# '노선명' 컬럼이 가지고 있는 데이터 분포 확인
df['노선명'].value_counts()

### 3. 정렬

In [18]:
# '승차총승객수' 기준으로 데이터 정렬(오름차순)
df.sort_values(by=['승차총승객수'], ascending=True)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
4743   20260508  경의선        운천       1       4  20260511
2664   20260505  경의선        검암       1       0  20260508
16688  20260528  6호선       연신내       1       0  20260531
7611   20260513  6호선        신내       1       0  20260516
11070  20260518  일산선        지축       1       0  20260521
...         ...  ...       ...     ...     ...       ...
13541  20260522  1호선       서울역   97514   98036  20260525
8674   20260515  2호선        강남   98157   96835  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
118    20260501  2호선      홍대입구  101927  115875  20260504

[19131 rows x 6 columns]

In [19]:
# '승차총승객수' 기준으로 데이터 정렬(내림차순)
df.sort_values(by=['승차총승객수'], ascending=False)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8674   20260515  2호선        강남   98157   96835  20260518
13541  20260522  1호선       서울역   97514   98036  20260525
...         ...  ...       ...     ...     ...       ...
7066   20260512  경의선        계양       1       0  20260515
15461  20260526  경원선        창동       1       0  20260529
7065   20260512  경의선        운천       1       3  20260515
16916  20260528  일산선        지축       1       0  20260531
17389  20260529  일산선        지축       1       0  20260601

[19131 rows x 6 columns]

In [20]:
# '승차총승객수' 기준으로 데이터 정렬(내림차순), 상위 10개 조회
df.sort_values(by=['승차총승객수'], ascending=False).head(10)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8674   20260515  2호선        강남   98157   96835  20260518
13541  20260522  1호선       서울역   97514   98036  20260525
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
17330  20260529  2호선        강남   96864   95651  20260601
13571  20260522  2호선        강남   96755   95209  20260525
4336   20260508  2호선        강남   96539   95218  20260511
8643   20260515  1호선       서울역   96164   95369  20260518

In [21]:
# '하차총승객수' 기준으로 데이터 정렬(내림차순), 상위 10개 조회(슬라이싱)
df.sort_values(['하차총승객수'], ascending=False)[0:10]

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
682    20260502  2호선      홍대입구  100394  111108  20260505
9497   20260516  2호선      홍대입구   93826  105809  20260519
14108  20260523  2호선      홍대입구   93902  105501  20260526
1898   20260504  2호선      홍대입구   91747  101530  20260507
18406  20260530  2호선      홍대입구   90426  101159  20260602
5217   20260509  2호선      홍대입구   88321   99335  20260512
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
13541  20260522  1호선       서울역   97514   98036  20260525

### 4. 선택

In [22]:
# '사용일자' 컬럼을 인덱스로 지정하여 df2 객체를 생성
df2 = df.set_index('사용일자')
df2

          노선명     역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  5호선     방이    5527    5357  20260504
20260501  5호선    둔촌동   10441    9979  20260504
20260501  5호선    상일동   10541    9932  20260504
20260501  5호선     고덕    7456    7257  20260504
20260501  5호선     명일    6377    6251  20260504
...       ...    ...     ...     ...       ...
20260531  8호선  단대오거리    6782    6559  20260603
20260531  8호선     신흥    3732    3895  20260603
20260531  8호선     수진    4223    3812  20260603
20260531  8호선     모란    3406    2806  20260603
20260531  8호선    남위례    4515    4530  20260603

[19131 rows x 5 columns]

In [23]:
print(df.head(3))
print('-'*100)
print(df2.head(3))

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
----------------------------------------------------------------------------------------------------
          노선명   역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  5호선   방이    5527    5357  20260504
20260501  5호선  둔촌동   10441    9979  20260504
20260501  5호선  상일동   10541    9932  20260504

In [24]:
# 인덱스 검색 : loc, iloc
df2.iloc[1]

노선명            5호선
역명             둔촌동
승차총승객수       10441
하차총승객수        9979
등록일자      20260504
Name: 20260501, dtype: object

In [25]:
# 20260510 일자 데이터 검색
df2.loc[20260510]

          노선명    역명  승차총승객수  하차총승객수      등록일자
사용일자
20260510  7호선  태릉입구    6549    6519  20260513
20260510  5호선    신길    3197    3374  20260513
20260510  9호선  양천향교    5221    5473  20260513
20260510  9호선    가양   13415   13294  20260513
20260510  9호선    증미    3114    3300  20260513
...       ...   ...     ...     ...       ...
20260510  중앙선    양평    3155    2873  20260513
20260510  중앙선    원덕     479     373  20260513
20260510  중앙선    용문    4829    4286  20260513
20260510  중앙선    지평      63      70  20260513
20260510  2호선    방배    8554    8679  20260513

[617 rows x 5 columns]

In [27]:
# 일반 데이터 검색 : 팬시, 불린, query
# '노선명' 컬럼의 '2호선' 데이터 조회
# 불린 인덱싱 조건 : df2['노선명'] == '2호선'
df2[df2['노선명'] == '2호선']

          노선명         역명  승차총승객수  하차총승객수      등록일자
사용일자
20260501  2호선  용두(동대문구청)    1980    1746  20260504
20260501  2호선      신정네거리    7710    7364  20260504
20260501  2호선       양천구청    4845    4751  20260504
20260501  2호선        도림천     814     803  20260504
20260501  2호선        신설동    3984    3453  20260504
...       ...        ...     ...     ...       ...
20260531  2호선        신설동    3960    3664  20260603
20260531  2호선        도림천     910    1127  20260603
20260531  2호선       양천구청    3858    3948  20260603
20260531  2호선      신정네거리    6203    6115  20260603
20260531  2호선  용두(동대문구청)    1417    1393  20260603

[1550 rows x 5 columns]

In [28]:
# 일반 데이터 검색 : 팬시, 불린, query
# '노선명' 컬럼의 '2호선' 데이터 조회
# query 조건 : '노선명 == "2호선"'
df2.query('노선명 == "2호선"')
df2.query('노선명 == "2호선"')['노선명'].count()

np.int64(1550)

In [29]:
# '승차총승객수'이 50000명 이상인 '역명' 조회
# 불린 인덱싱 : df2['승차총승객수'] >= 50000
df2[df2['승차총승객수'] >= 50000]['역명']
df2[df2['승차총승객수'] >= 50000]['역명'].unique()

array(['고속터미널', '홍대입구', '강남', '잠실(송파구청)', '성수', '서울역', '수원', '용산',
       '서울대입구(관악구청)', '선릉', '을지로입구', '구로디지털단지', '신도림', '신림', '삼성(무역센터)',
       '역삼', '가산디지털단지', '사당', '혜화', '종각'], dtype=object)

In [30]:
# '승차총승객수'이 50000명 이상인 '역명' 조회
# 쿼리 : '승차총승객수 >= 50000'
df2.query('승차총승객수 >= 50000')
df2.query('승차총승객수 >= 50000')['역명'].unique()

array(['고속터미널', '홍대입구', '강남', '잠실(송파구청)', '성수', '서울역', '수원', '용산',
       '서울대입구(관악구청)', '선릉', '을지로입구', '구로디지털단지', '신도림', '신림', '삼성(무역센터)',
       '역삼', '가산디지털단지', '사당', '혜화', '종각'], dtype=object)

In [31]:
# '승차총승객수'이 50000명 이상이고, '역명' 이름이 '강남'인 데이터 조회
df2[(df2['승차총승객수'] >= 50000) & (df2['역명'] == '강남')]
df2[(df2['승차총승객수'] >= 50000) & (df2['역명'] == '강남')].count()

노선명       24
역명        24
승차총승객수    24
하차총승객수    24
등록일자      24
dtype: int64

In [33]:
# '승차총승객수'이 50000명 이상이고, '역명' 이름이 '강남'인 데이터 조회
df2.query('승차총승객수 >= 50000 & 역명 == "강남"')
df2.query('승차총승객수 >= 50000 & 역명 == "강남"').count()

노선명       24
역명        24
승차총승객수    24
하차총승객수    24
등록일자      24
dtype: int64

In [34]:
# '승차총승객수' 컬럼의 최대값
df['승차총승객수'].max()

101927

In [36]:
# '승차총승객수' 컬럼의 최소값
df['승차총승객수'].min()

1

In [37]:
# '승차총승객수' 컬럼의 최대값, '하차총승객수' 컬럼의 최소값을 조회
df.agg(
    {
        '승차총승객수': 'max',
        '하차총승객수': 'min'
    }
)

승차총승객수    101927
하차총승객수         0
dtype: int64

In [38]:
# '승차총승객수','하차총승객수' 컬럼의 최대값, 최소값, 평균값을 조회
df[['승차총승객수', '하차총승객수']].agg(['max', 'min' ,'mean', 'median'])

              승차총승객수        하차총승객수
max     101927.00000  115875.00000
min          1.00000       0.00000
mean     11811.35074   11759.56364
median    8396.00000    8135.00000

### 5. 삭제

In [39]:
# 행기준으로 삭제, 0번지 행 삭제, df
df.drop(0)

           사용일자  노선명             역명  승차총승객수  하차총승객수      등록일자
1      20260501  5호선            둔촌동   10441    9979  20260504
2      20260501  5호선            상일동   10541    9932  20260504
3      20260501  5호선             고덕    7456    7257  20260504
4      20260501  5호선             명일    6377    6251  20260504
5      20260501  5호선  굽은다리(강동구민회관앞)    8230    7693  20260504
...         ...  ...            ...     ...     ...       ...
19126  20260531  8호선          단대오거리    6782    6559  20260603
19127  20260531  8호선             신흥    3732    3895  20260603
19128  20260531  8호선             수진    4223    3812  20260603
19129  20260531  8호선             모란    3406    2806  20260603
19130  20260531  8호선            남위례    4515    4530  20260603

[19130 rows x 6 columns]

In [40]:
# 행기준으로 삭제, 3, 5, 7 번지 행 삭제, df
df.drop([3, 5, 7])

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자
0      20260501  5호선     방이    5527    5357  20260504
1      20260501  5호선    둔촌동   10441    9979  20260504
2      20260501  5호선    상일동   10541    9932  20260504
4      20260501  5호선     명일    6377    6251  20260504
6      20260501  5호선     길동    7758    7877  20260504
...         ...  ...    ...     ...     ...       ...
19126  20260531  8호선  단대오거리    6782    6559  20260603
19127  20260531  8호선     신흥    3732    3895  20260603
19128  20260531  8호선     수진    4223    3812  20260603
19129  20260531  8호선     모란    3406    2806  20260603
19130  20260531  8호선    남위례    4515    4530  20260603

[19128 rows x 6 columns]

In [41]:
# '등록일자' 컬럼 삭제
df.drop('등록일자', axis=1)

           사용일자  노선명     역명  승차총승객수  하차총승객수
0      20260501  5호선     방이    5527    5357
1      20260501  5호선    둔촌동   10441    9979
2      20260501  5호선    상일동   10541    9932
3      20260501  5호선     고덕    7456    7257
4      20260501  5호선     명일    6377    6251
...         ...  ...    ...     ...     ...
19126  20260531  8호선  단대오거리    6782    6559
19127  20260531  8호선     신흥    3732    3895
19128  20260531  8호선     수진    4223    3812
19129  20260531  8호선     모란    3406    2806
19130  20260531  8호선    남위례    4515    4530

[19131 rows x 5 columns]

In [42]:
# '등록일자', '역명' 컬럼 삭제
df.drop(['등록일자','역명'], axis=1)

           사용일자  노선명  승차총승객수  하차총승객수
0      20260501  5호선    5527    5357
1      20260501  5호선   10441    9979
2      20260501  5호선   10541    9932
3      20260501  5호선    7456    7257
4      20260501  5호선    6377    6251
...         ...  ...     ...     ...
19126  20260531  8호선    6782    6559
19127  20260531  8호선    3732    3895
19128  20260531  8호선    4223    3812
19129  20260531  8호선    3406    2806
19130  20260531  8호선    4515    4530

[19131 rows x 4 columns]

### 6. 연산

In [43]:
# '승차총승객수' 컬럼에  10을 더하여, '승차총승객수_10' 컬럼을 추가
df['승차총승객수_10'] = df['승차총승객수'] + 10
df

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10
0      20260501  5호선     방이    5527    5357  20260504       5537
1      20260501  5호선    둔촌동   10441    9979  20260504      10451
2      20260501  5호선    상일동   10541    9932  20260504      10551
3      20260501  5호선     고덕    7456    7257  20260504       7466
4      20260501  5호선     명일    6377    6251  20260504       6387
...         ...  ...    ...     ...     ...       ...        ...
19126  20260531  8호선  단대오거리    6782    6559  20260603       6792
19127  20260531  8호선     신흥    3732    3895  20260603       3742
19128  20260531  8호선     수진    4223    3812  20260603       4233
19129  20260531  8호선     모란    3406    2806  20260603       3416
19130  20260531  8호선    남위례    4515    4530  20260603       4525

[19131 rows x 7 columns]